apiVersion: v1
kind: Namespace
metadata:
  name: my-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-flags
  namespace: my-app
data:
  myflag: "false"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ctff-configmap-reader
  namespace: my-app
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["my-flags"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ctff-allowed-my-app
  namespace: my-app
subjects:
  - kind: ServiceAccount
    namespace: ctff
    name: ctff-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ctff-configmap-reader
